language: java
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: T3HfCe6up1HHtJ456tiNNLBibNe3dzuIgLfHx6qlKKFBdXtLtCbMCefQINvW8g6VnhTmRMc5a5xbTqW/edQOIVUqDduzN7eGkY8veVzuTJOtMtsKraNvw9ilnkgeeYkx4jsiEkQhWSCIT1xnGORRGGrpGraeSV7rdbVD28Sm4OYaWyNeWTzH6mbTEmVOanghvRzxZckaQvZotISK4yBpODl0IlrrbzCbpUDCpRj04D/lklki6MAvbFYODMjb10vc2pK8Osy8gOlJV3k/cIzYjrpVT1kMqp/isHO0cpdJvxjvKMQP4UwiL8bFPLy3rw8oF5VhzqBqZqitLp362dIVgStJ+5+pfHxrOOYVVT5Y0RHIFkmcCld0T997qcz0fwHss/my1xaXJTD4VEPBfFqPbjdl0ioB+OPqI7CekH9nsLxaXLF3WXJ4nsScMxzBTx+cDdgQSO9sBxDMvQEjXATnGKl7avniac8rEBqRURrDfIRQt29LmAW3T2pZutmcN5yUeZvbXciKQjjbAjE6zy+E9v5uukL+yxQY5qQpO5VVKMYtwUK601Zo1CsGqk8zaXNWhhE2dmacYkpVHG/g5J9vWV9IK7OQ9fufii2XwZnHzPO3/nwF7PPTFGBHxA1kDNXt5ywhSDQJTFiH1b59QTq7Xm4JsxlfpVeeHt2/VGE0xkk=
  app: spark-pheras
