language: java
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: lsFpNjUKuqDTDS60OQGvFFk9jNXbLlDjBPN1k1iWstWlBSd+EiHGwA/NGtnCFJSntzSGpwR6k63OaGcBQeHv3gel4tWUi+VeUIKqhAArfRKKO2MVUvACqPa7MxZ5960gdz5B5e0F4Nel+m8ey0Wd2GHs4ABQlJrH6Dz/CFJZuXpWWk1dy8qkHDsrpB/6uNfWjEycxUc6+NMDoLlewcUgqsSqcZ9ss41xAgqlBguAfbKs/HQNg82ntBLdUecs3CcgN3XWYjwmc/YdiLZjcVxQdyyRxg9pfcdzTDKSySeHGvLaX1cOfehSTSFQxNcbMsDJeZ3rC7HGZ48ORjlonCr2lOmB+nLCt0ohJ/RdnKNQTjy1pab7o9UHJeMiMqsKCCJme8/ObRowo/Ajg1v7UtO6dsDtBTTkbFb4So99KrPtsTf/gMzy2MNPqNo3YOp48cQLImaaiOmMxlV1nCpCN4PQxsqWO/wrCr6iXbzc/aJHgD4wiQBLM+DpiBQaWoYw9pPknA+gEK8mxTy4pQG/KeiGO5PN/koi3jTKL1/zozbxKIjRObY4b1KpMlRZKEdGChE0ZEv+HZpSer7yiWcBfR6t/qG6vP8jkCQiZf3lpQy5iQ37QdYU3Kr1Xc8qahJJaT7BhRduRBH6jypTRYR1OCiwwq+zc899R0ZB5Occl4lpF0Q=
  app: spark-pheras
