language: java
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: quVnwIur6rA+25/mYkdf+X6p9Wwvw8c6xytGh39/FzMgXMy6FN+YzZmbWXnxWuS+iXHVzS+d3YYFU5vCyjL50+uNiMN4KtHedg+Af7rNWr+AQpTgswPsea4cLVnWHA+GUwYDEzkb0HnnqU2yayyVyGFa0tzAqzPBoBFXkakdzWI+qafw+IE+Y760R23xv0lQ4WR/c/LD/U+AJ3OPbrGsKOqVBVqO71dGhsR14GoVJvwA0W5ETJQ9ozaT3GM3z5ADkyic2v+5qYz9QHXoTrYrzGTUaMAoO9ByJG7kHqRVh4rACi81jfr5OT/4zztp4AeQu6aEfX/q2uatEK02hYz1PeE5FA1uWcdX4BQ2SPzaq8GkAWXcW4lCg1NUKYPUvxUFoFlbkjB69VKSqgNwsxAU9P7VE4A8pwtSYTdEgqOWIZFgD/xN+a1vIjPk1NCpMi0o84oXn+oKH/QNJzASLbq/ns+ZsVEgogoK2MgPsqYYC+ZcovaPR6A3GsXNeoSeOLD6SZqNI9iW2SrNvPCHmO/Hx8vBcxhXSo3cH1TsJTY9G0GGM+RFuEtCaQDXy/6a4q2dqPohZW1+tO2y/nKCW5KMwOjSqs4f9dVLsL+E0RvyrXfpvqtLckQ6d0GGFv7EiKp92TtPE5BUvke8c5HDuaIK6wfkW9zlIPprixWGwwk63zg=
  app: 
    master: spark-pheras
