language: java
deploy:
  provider: heroku
  api_key:
    secure: kyLYYqUJ2iFCFBQi0zqeVsn4DUE1c9NWmwRiK9JdyWzdpwrOQdeOWATQSkjrPkfmwzIdgeDlly7QbKrrK4WqUX9rI4SP+MfzAd5TSG7zMDH3upCI0QYd4ITBkQph9jNdZHEH+ma5jkfmqsja7zlurNGMqtXPbwPbtQ3Qa1uKbhjC0zvCK/VPgHnxWZDxdhArjmtIX9zGIghErnztjlEc3661ncLyRaUJb8utl2tqhyaNBdjP9yYTxYTKdi9kiEwn6nOJAGIYIiVBOShWC9M47m1LUD8VV8ppkWSAj2xrjlLyEEzdQOd+vF3RTNz3ltoaKztityoH0xGfWt42YT9EoXbZa8DV5PTOS4TnrcmcDPEygUT2GefvN7fahv5VsEWkar0A7Qlk9Lkfhe1fUGKUABm/SUEvDS/a+4h9f17hluQex9kabtKg6qoP5oNISbfNYP7FriADFjp4d7h+lQAYZynD2egecU1sp9MiGyrJ8/CQpQMfppbTCb6pdVW9T3if1iUT7pUAQVHG2i7eyU9XiM4WzQuay2eNtSziQzfEsc8seLmSCfp0lo1RMzy/vpgoykRAGQQ0EaQevKmtMEP/hA6r8V/OUznQF9Q6KwugxpedHvHp5kviSnQ3uSjwzLarzYZ2B+Sq4mBnTf/mlJJC+Ar4Od7mOrGkyuoDSC6KfR0=
  app: spark-pheras
