language: java
deploy:
  provider: heroku
  api_key:
    secure: "PsMcK3JHmb1v/yHZ/fJbjzlGBD6N4RUzhD49z3xU9G4mEdGnTQGs8b0e0rq0JrYvs+DfaZYaMUJ9gC1UQfzj6fUFjyRs2lN2Jaxp3nd4iAKcHiYlSZNYgjvsfr4/lId6oPNKEl20T71APvsHdz95C9NZ6tG3FNin2mLzNSAOkacKw13PdBiogCuz/M6plWUX89ucMF7yE8iTTzN1JBsblWQ2yvvlhmsDGO28RaxtTD/uwiG7Y4ygE6aOnDhVQEd+2V+OoKgOw2o9qOuXNMeHHhpK0hZ+iqH6zZ8ylm1TD6Rih5spiPHMZAXhyUqvHDAiypbeSSuz6ABdFX339Z8Nuy6gyAhOISbbrnbhfpl4Wq+7VwQkikfrRjt2T1PbSVMqMK25Vk5NORcM/FK0ixHVzpSjh2O9TOw8cKgjNIfhVquA3+a81vCfU0W1zT9O3M5Ews3i+bxOm13I4eDSnipuA1vT2oFDof041Es67xUUbbBiI0opmtzBvTrdbYbM+mVxTIWzEXGZ8t7vvga9E7FXN9r+0zpAi713HDeHMmOvsLWbLNoJOUrjtNUKWJITSMfKPak+IMTqAXjiFCabZgZZ5WSDKqpmCJ6T+/V+5kXPoMFy+Zkghqq3XcLzs29LFffy34otr1DGfmRASHJJIAgHVC8gJUKcUVtKXjkxN9DxhEo="
  app: spark-pheras
